export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_REPOS = 'GET_REPOS';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
// Social Tab
export const GET_SELECTED_ITEM = 'GET_SELECTED_ITEM';
export const SET_SELECTED_ITEM = 'SET_SELECTED_ITEM';
export const SET_ACTIVE_SECTION = 'SET_ACTIVE_SECTION';
export const GET_ACTIVE_SECTION = 'GET_ACTIVE_SECTION';
export const GET_FRIEND_PROFILES = 'GET_FRIEND_PROFILES';
export const SOCIAL_ERROR = 'SOCIAL_ERROR';
// Posts
export const GET_POSTS = 'GET_POSTS';
export const POST_ERROR = 'POST_ERROR';
